#!/bin/bash
echo "Best School" > \*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)
echo "Holberton School" > \\\*\\\\"'\"Holberton School\"\\'"\\\\\*\$\\\?\\\*\\\*\\\*\\\*\\\*\:\)
\*\\'"Holberton School"\'\\*$\?\*\*\*\*\*:)
